---

fabric_name: FABRIC 
# Match with the file name (case sensitive) and the inventory group at the top of the fabric

underlay_rfc5549: true



p2p_uplinks_mtu: 1500

local_users: # Password is arista
  ansible_local:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: default # In Arista labs set the mgmt vrf for default


dns_domain: atd.lab
