---
- name: Add VLANs
  hosts: leaf1-DC1

  tasks:
    - name: Add a single VLANs
      arista.eos.vlans:
        config:
          - vlan_id: 10
            state: active
          - vlan_id: 54
            state: active
        state: parsed
      register: parsed
    - name: Print rendered  
      debug:
        msg: "{{ parsed }}"
