---
- name: Create direcoties
  hosts: all
  tasks:
  # - name: Create unique directory per devices
  #   file:
  #     path: "./configs/{{ inventory_hostname }}"
  #     state: directory
  - name: Copy ATD-INFRA to every directory
    copy:
      src: "{{ lookup('env','PWD') }}/configs/static/ATD-INFRA.cfg"
      dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}/ATD-INFRA.cfg"
      mode: "0644"

- name: Generate management configs
  hosts: DC1, DC2
  tasks:
    - name: Load up Variable as a dictonary
      include_vars:
        file: ../vars/mgmt.yml
        name: mgmt
    - name: Generate config from template for leafs
      template:
        src: "{{ lookup('env','PWD') }}/templates/mgmt.j2"
        dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_mgmt.cfg"
        mode: '0644'

- hosts: Leafs_DC1, Leafs_DC2
  name: Generate config from template
  tasks:
    - name: Load up Variable as a dictonary
      include_vars:
        file: ../vars/underlay.yml
        name: underlay
    - name: Generate config from template for leafs
      template:
        src: "{{ lookup('env','PWD') }}/templates/underlay_leaf.j2"
        dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_underlay.cfg"
        mode: '0644'

- name: Generate config from template for spines
  hosts: Spines_DC1, Spines_DC2
  tasks:
    - name: Load up Variable as a dictonary
      include_vars:
        file: ../vars/underlay.yml
        name: underlay
    - name: Generate config from template for leafs
      template:
        src: "{{ lookup('env','PWD') }}/templates/underlay_spine.j2"
        dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_underlay.cfg"
        mode: '0644'

- name: Assemble all files into one
  hosts: all
  tasks:
    - name: Do the actual assembling
      assemble:
        src: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}"
        dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_final.cfg"
        mode: "0644"
