---
- name: Upload partial configs to EOS directly
  hosts: DC1, DC2
  tasks:
  - name: Upload to EOS device
    arista.eos.eos_config:
      src: "../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_final.cfg"
      # save_when: always
      replace: config
